/**
 * Rewrite tab-panels image paths to sized variants.
 * - full:    assets/tab-panels/{name}.webp           (lightbox / expanded only)
 * - small:   assets/tab-panels/small/{name}.webp     (800w; gallery cards, coverflows)
 * - preview: assets/tab-panels/preview/{name}.webp   (256w; timeline thumbs)
 * Generated by `npm run images` for missing files only (pre-commit, not quartz build).
 * Non-tab-panels paths (coverflow/, icons/, etc.) pass through unchanged.
 */
export function imageVariant(src: string, variant: "preview" | "small" | "full"): string {
  if (!src) return src
  if (src.startsWith("http://") || src.startsWith("https://")) return src

  const normalized = src.startsWith("/") ? src : `/${src.replace(/^\.\//, "")}`
  const match = normalized.match(/^(\/assets\/tab-panels\/)(?:preview\/|small\/)?([^/?#]+)$/i)
  if (!match) return src

  const [, base, filename] = match
  if (variant === "full") return `${base}${filename}`
  return `${base}${variant}/${filename}`
}
